{{- if and (.Values.plugins.enabled) (gt (len .Values.plugins.list) 0) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fluentd.fullname" . }}-plugins
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
data:
  install-plugins.sh: |-
    #!/usr/bin/env sh
    set -eu
    {{- range .Values.plugins.list }}
    fluent-gem install {{ . }}
    {{- end }}
    exec {{ .Values.plugins.runCommand }}
{{- end }}
