apiVersion: v1
name: istio-operator
version: 1.0.0
appVersion: 1.6.1
description: A Helm chart for the Istio Operator.
keywords:
- kubernetes
- istio
- operator
- service
- mesh
home: https://istio.io/
icon: https://istio.io/favicons/android-192x192.png
sources:
- https://github.com/istio/istio/operator
maintainers:
- name: stevehipwell
  email: steve.hipwell@github.com
